CREATE TABLE Cliente (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Nome VARCHAR(100) NOT NULL, 
  Cpf VARCHAR(11) NOT NULL UNIQUE,
  Email VARCHAR(100) NOT NULL,
  DataCadastro DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  EmpresaId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT UQ_Clientes_Cpf UNIQUE (Cpf),
  CONSTRAINT FK_Clientes_Empresas
  FOREIGN KEY (EmpresaId) REFERENCES Empresas(Id)
  );
